version: '2'

services:
  python3.4:
    image: python:3.4-slim
    command: /bin/bash run_test.sh
    working_dir: /var/app
    links:
      - postgres
    volumes:
      - ./:/var/app

  python3.5:
    image: python:3.5-slim
    command: /bin/bash run_test.sh
    working_dir: /var/app
    links:
      - postgres
    volumes:
      - ./:/var/app

  python3.6:
    image: python:3.6-slim
    command: /bin/bash run_test.sh
    working_dir: /var/app
    links:
      - postgres
    volumes:
      - ./:/var/app

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
