version: '2'

services:

  tox:
    build: .
    links:
      - postgres
    volumes:
      - ./thunderstorm_auth/:/src/thunderstorm_auth
      - ./test/:/src/test
      - ./test_results/:/app/test_results
      - ./Makefile:/src/Makefile
      - ./.flake8:/src/.flake8

  dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/src/thunderstorm_auth

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
