version: '2'

services:
  python34:
    image: "${REGISTRY}/artsalliancemedia/python:3.4-slim"
    command: make test
    working_dir: /var/app
    environment:
      - DB_NAME=test_auth_lib_py34
    volumes:
      - ./:/var/app
    depends_on:
      - postgres

  python35:
    image: "${REGISTRY}/artsalliancemedia/python:3.5-slim"
    command: make test
    working_dir: /var/app
    environment:
      - DB_NAME=test_auth_lib_py35
    volumes:
      - ./:/var/app
    depends_on:
      - postgres

  python36:
    image: "${REGISTRY}/artsalliancemedia/python:3.6-slim"
    command: make test
    working_dir: /var/app
    environment:
      - DB_NAME=test_auth_lib_py36
    volumes:
      - ./:/var/app
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
