version: '2'

services:

  tox:
    build: .
    volumes:
      - ./thunderstorm_auth/:/src/thunderstorm_auth
      - ./test/:/src/test

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
